# Generated by Django 4.1.13 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_todo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("soil_moisture", models.FloatField()),
                ("temperature", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Sensor Data",
            },
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
