# Generated by Django 4.1.13 on 2024-05-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_mediacontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
